[package]
name = "webdriver_test"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
fantoccini = "0.21"
serde_json = "1.0"